---

name: lint-dockerfile

on:
  pull_request:
    types: [opened, reopened, synchronize]
permissions: write-all
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: 'Dockerfile'
          recursive: true
