name: lint-docker
on:
  pull_request:
    types: [opened, reopened, synchronize]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  hadolint:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v5
      - name: hadolint
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: 'Dockerfile'
          recursive: true
