name: preset-pr
on:
  pull_request:
    types: [opened, reopened]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
permissions:
  pull-requests: write
  issues: write
jobs:
  call-preset-pr:
    uses: jnicrimi/reusable-workflows/.github/workflows/called-preset-pr.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
